export { default as Comprar } from './comprar/Comprar'
export { default as Nosotros } from './nosotros/Nosotros'
export { default as Footer } from './footer/Footer'
export { default as Contacto } from './contacto/Contacto'
export { default as ItemDetailContainer } from './itemdetailcontainer/ItemDetailContainer'